name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  actionlint:
    uses: ./.github/workflows/actionlint.yml
    secrets: inherit

  deploy:
    needs: [tests, lint, actionlint]
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      DEPLOY_REF:  ${{ secrets.DEPLOY_REF }}     # optional
      POST_DEPLOY: ${{ secrets.POST_DEPLOY }}    # optional
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g pm2
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: true
      - name: Trust server
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
      - name: Guard required env
        shell: bash
        run: |
          : "${DEPLOY_HOST:?DEPLOY_HOST is empty}"
          : "${DEPLOY_USER:?DEPLOY_USER is empty}"
          : "${DEPLOY_PATH:?DEPLOY_PATH is empty}"

      - name: Force origin to HTTPS on server
        shell: bash
        run: |
          set -e
          ssh -o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes \
            "${DEPLOY_USER}@${DEPLOY_HOST}" '
              set -e
              for d in "'"$DEPLOY_PATH"'/source" "'"$DEPLOY_PATH"'/current"; do
                if [ -d "$d/.git" ]; then
                  echo "Fixing remote in $d"
                  git -C "$d" remote set-url origin https://github.com/scatauk/nela-api.git || true
                  git -C "$d" remote -v
                fi
              done
            '
      - name: PM2 deploy
        run: pm2 deploy ecosystem.config.js production
